/* Banco de preguntas - Emprendedurismo
   Formato: JSON válido dentro de JS para funcionar con file:// sin fetch.
   Para agregar preguntas: copia un objeto, cambia el id (DOC-###) y respeta los campos.
   tipo: "multiple" (4 opciones) | "vf" (opciones ["Verdadero","Falso"])
   respuesta: índice de la opción correcta (0-based)
   dificultad: "base" | "detalle" | "trampa"

   CRITERIOS DE REDACCIÓN (basados en JHU-CTEI, UT Austin, ACS/NBME, Haladyna et al. 2002
   y guía UNED de redacción de exámenes):
   1. Enunciado autocontenido: se responde sin ver las opciones y sin tener el PDF a la mano.
   2. Nada de "según el documento X / la portada dice / en el ejemplo Y": los datos necesarios
      van DENTRO del enunciado (mini-caso) o la pregunta evalúa el concepto.
   3. Los ejemplos del material se usan como casos con datos incluidos para CLASIFICAR o
      DECIDIR, nunca como datos a recordar (nombres, cifras, frases literales).
   4. Sin trivia meta: autores de fichas, páginas, frases literales, cifras de ejemplos.
   5. Sin enunciados negativos ni "todas las anteriores".
   6. Distractores plausibles y homogéneos (confusiones reales entre conceptos vecinos).
   7. Las V/F discriminan conceptos confundibles, no repiten definiciones copiadas.
   8. Mezcla Bloom: recuerdo de marcos importantes, comprensión (clasificar/explicar) y
      aplicación (mini-caso/cálculo).
*/
var DOC_NAMES = {
  "PV1": "1- Propuesta de Valor.pdf",
  "PV2": "2- Material de apoyo - propuesta de valor.pdf",
  "MKT8": "Clase_8_Mercadotecnia.pdf",
  "COST": "Costos en servicios.pdf",
  "EJPV": "Ejemplos y estructura de propuesta de valor.pdf",
  "SEG1": "Segmento de Cliente - parte 01 (1).pdf",
  "SEG2": "Segmento de Cliente - parte 02.pdf"
};

var DOCS = [
  { id: "PV1", titulo: "1- Propuesta de Valor", archivo: "pdfs/01-propuesta-de-valor.pdf", descripcion: "Categorías, beneficios, errores y lienzo con ejemplo Tutorez." },
  { id: "PV2", titulo: "2- Material de apoyo - propuesta de valor", archivo: "pdfs/02-material-apoyo-propuesta-valor.pdf", descripcion: "Definición técnica, 8 pasos, factores LOGRO/GANANCIA/ESTATUS/CONFIANZA y criterios de redacción." },
  { id: "MKT8", titulo: "Clase 8 - Mercadotecnia", archivo: "pdfs/03-clase-8-mercadotecnia.pdf", descripcion: "CANVAS, marca, 4P, investigación de mercado y ejemplo StockFácil." },
  { id: "COST", titulo: "Costos en servicios", archivo: "pdfs/04-costos-en-servicios.pdf", descripcion: "Costos fijos/variables, costo por usuario, precio de venta y presupuesto digital." },
  { id: "EJPV", titulo: "Ejemplos y estructura de propuesta de valor", archivo: "pdfs/05-ejemplos-estructura-propuesta-valor.pdf", descripcion: "Estructura de 7 elementos y ejemplo consolidado web sin programar." },
  { id: "SEG1", titulo: "Segmento de Cliente - parte 01", archivo: "pdfs/06-segmento-cliente-parte-01.pdf", descripcion: "Plantilla de clientes potenciales y ejemplo Elisa Rodríguez / Wazlt." },
  { id: "SEG2", titulo: "Segmento de Cliente - parte 02 - Mapa de empatía", archivo: "pdfs/07-segmento-cliente-parte-02.pdf", descripcion: "Mapa de empatía de 6 cuadrantes y ejemplo Sandy Peterson / cafetería." }
];

var QUESTION_BANK = [
  // ============ PV1 (20) ============
  { id: "PV1-001", doc: "PV1", tema: "Definición", tipo: "multiple", pregunta: "Una propuesta de valor responde, en el fondo, a la pregunta que se hace el cliente:", opciones: ["¿Cómo bajan sus costos de producción?", "¿Por qué debería comprarte a ti?", "¿Cuántos empleados tiene la empresa?", "¿Dónde está registrada la marca?"], respuesta: 1, explicacion: "La propuesta de valor responde a '¿por qué debo comprarte a ti?': comunica por qué elegirte frente a otras opciones.", fuente: "PV1 - definición", dificultad: "base" },
  { id: "PV1-002", doc: "PV1", tema: "Definición", tipo: "multiple", pregunta: "Ofrecer valor a los clientes significa principalmente:", opciones: ["Tener siempre el precio más bajo del mercado", "Mejorar su vida resolviendo los problemas que enfrentan al intentar completar un trabajo", "Invertir más en publicidad que la competencia", "Igualar la propuesta del líder del mercado"], respuesta: 1, explicacion: "Valor = entender cómo mejorar la vida del cliente resolviéndole los problemas que enfrenta al completar un trabajo.", fuente: "PV1 - definición", dificultad: "base" },
  { id: "PV1-003", doc: "PV1", tema: "Propuesta exitosa", tipo: "multiple", pregunta: "¿Cuál de estas frases SÍ describe una propuesta de valor exitosa?", opciones: ["Habla directamente a su segmento de clientes con un mensaje claro y con evidencia del valor", "Usa un texto largo y técnico para sonar profesional", "Evita mencionar a quién va dirigida para llegar a más gente", "Promete beneficios sin ninguna prueba que los respalde"], respuesta: 0, explicacion: "Exitosa = habla al segmento, clara y concisa, comunica la promesa de marca y presenta evidencia del valor.", fuente: "PV1 - propuesta exitosa", dificultad: "detalle" },
  { id: "PV1-004", doc: "PV1", tema: "Categorías", tipo: "multiple", pregunta: "Una tienda ofrece 'devolución gratis por 30 días y garantía extendida sin costo'. ¿A qué categoría de propuesta de valor corresponde?", opciones: ["Reducción de riesgo, porque disminuye la incertidumbre al pagar y decidir", "Ahorro, porque siempre implica el precio más bajo", "Diseño, porque mejora la estética del producto", "Experiencias, porque crea momentos inolvidables"], respuesta: 0, explicacion: "Reducción de riesgo = reducir la incertidumbre al pagar o tomar una decisión (garantías, devoluciones, pruebas).", fuente: "PV1 - categorías", dificultad: "detalle" },
  { id: "PV1-005", doc: "PV1", tema: "Categorías", tipo: "multiple", pregunta: "Una plataforma que pone en contacto a tutores con padres de familia que buscan clases para sus hijos entrega valor de:", opciones: ["Conectividad, porque facilita la conexión entre quienes ofrecen y quienes buscan", "Ahorro, porque garantiza los precios más bajos del mercado", "Diseño, porque el servicio es estéticamente atractivo", "Estatus social, porque otorga prestigio automático"], respuesta: 0, explicacion: "Conectividad = facilitar la conexión entre compradores y vendedores (o entre oferta y demanda).", fuente: "PV1 - categorías", dificultad: "detalle" },
  { id: "PV1-006", doc: "PV1", tema: "Categorías", tipo: "multiple", pregunta: "Un reloj de lujo se vende destacando que 'te hace ver y sentir bien'. Esa promesa corresponde a:", opciones: ["Ahorro", "Estatus social", "Conveniencia", "Rendimiento"], respuesta: 1, explicacion: "Estatus social = propuestas que te hacen ver y sentir bien frente a otros.", fuente: "PV1 - categorías", dificultad: "detalle" },
  { id: "PV1-007", doc: "PV1", tema: "Categorías", tipo: "vf", pregunta: "Pedir comida con una app que guarda tu dirección y paga en un clic entrega valor de conveniencia, porque hace la tarea más fácil y rápida. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: conveniencia = hacer algo más fácil o rápido de hacer.", fuente: "PV1 - categorías", dificultad: "base" },
  { id: "PV1-008", doc: "PV1", tema: "Beneficios", tipo: "multiple", pregunta: "Cuando una propuesta de valor es fuerte y diferenciada, la empresa puede lograr:", opciones: ["Cobrar precios mayores porque el cliente percibe más valor", "Dejar de conocer a sus clientes", "Vender sin dar ninguna evidencia del beneficio", "Ignorar por completo a la competencia"], respuesta: 0, explicacion: "Una PV exitosa permite atraer y convertir más clientes, fidelizarlos, capturar valor con mejores precios y superar competidores.", fuente: "PV1 - beneficios", dificultad: "detalle" },
  { id: "PV1-009", doc: "PV1", tema: "Errores", tipo: "multiple", pregunta: "Un equipo lanza la frase 'Somos los mejores, calidad total garantizada' sin pruebas ni validación con clientes. ¿Qué error comete?", opciones: ["Presenta una propuesta sin evidencias, poco clara y no probada en su segmento", "Usa demasiadas evidencias y datos comprobables", "Valida en exceso con su segmento de clientes", "Es demasiado claro y específico en su promesa"], respuesta: 0, explicacion: "Errores típicos: falta de evidencias del valor ofrecido, mensaje poco claro y propuesta no probada en el segmento.", fuente: "PV1 - errores", dificultad: "base" },
  { id: "PV1-010", doc: "PV1", tema: "Recomendaciones", tipo: "multiple", pregunta: "Al redactar tu propuesta de valor dudas entre una frase ingeniosa pero confusa y una frase simple que cualquiera entiende. ¿Qué debes preferir?", opciones: ["La frase ingeniosa, porque la creatividad vende sola", "La frase simple, porque la claridad va antes que la creatividad", "Llenarla de tecnicismos para sonar experto", "Escribirla en otro idioma para parecer internacional"], respuesta: 1, explicacion: "Regla: claridad antes que creatividad, usando las palabras que el propio segmento utiliza.", fuente: "PV1 - recomendaciones", dificultad: "detalle" },
  { id: "PV1-011", doc: "PV1", tema: "Lienzo - trabajos", tipo: "multiple", pregunta: "Un cliente quiere comprar una laptop visible en reuniones para proyectar éxito profesional. Ese trabajo es de tipo:", opciones: ["Funcional, porque resuelve un problema técnico", "Social, porque busca estatus y que lo vean bien", "Emocional, porque solo busca sentirse tranquilo", "Financiero, porque solo importa el precio"], respuesta: 1, explicacion: "Tareas sociales = estatus, destacar, poder o que lo vean bien. Funcionales = resolver un problema; emocionales = sentirse mejor.", fuente: "PV1 - trabajos del cliente", dificultad: "detalle" },
  { id: "PV1-012", doc: "PV1", tema: "Lienzo - frustraciones", tipo: "multiple", pregunta: "Un padre quiere contratar un tutor pero no sabe dónde buscar ni comparar opciones, así que ni siquiera empieza. Ese freno es una frustración de tipo:", opciones: ["Obstáculo, porque le impide iniciar la tarea o lo hace avanzar más lento", "Beneficio esperado, porque es algo que desea recibir", "Creador de alegría, porque genera un beneficio", "Requisito mínimo, porque sin eso el servicio no funciona"], respuesta: 0, explicacion: "Obstáculos = lo que impide iniciar una tarea o hace avanzar más lento. Resultados = características no deseadas de lo existente; riesgo = lo que puede salir mal.", fuente: "PV1 - frustraciones", dificultad: "detalle" },
  { id: "PV1-013", doc: "PV1", tema: "Lienzo - alegrías", tipo: "multiple", pregunta: "En el cuadrante de alegrías, ¿qué significan los 'requisitos mínimos'?", opciones: ["Lo básico sin lo cual el producto o servicio ni siquiera funcionaría como tal", "Los lujos inesperados que encantan al cliente", "Los deseos personales que el cliente no se atreve a pedir", "Los extras decorativos que suben el precio"], respuesta: 0, explicacion: "De menor a mayor: requisitos mínimos (sin esto no funciona), beneficios esperados, deseados y no esperados.", fuente: "PV1 - alegrías", dificultad: "detalle" },
  { id: "PV1-014", doc: "PV1", tema: "Mapa de valor", tipo: "multiple", pregunta: "Un 'aliviador de frustraciones' bien diseñado debe lograr que el cliente sienta que:", opciones: ["Se elimina o reduce su dolor: ahorra tiempo, dinero o esfuerzo y simplifica sus tareas", "Se le suman más funciones y beneficios extra", "Se vuelve más prestigioso y deseable", "Se le agregan sorpresas inesperadas"], respuesta: 0, explicacion: "Aliviadores = cómo eliminar o reducir el dolor: ahorro de dinero, tiempo o esfuerzo, sentirse mejor y tareas más simples.", fuente: "PV1 - aliviadores", dificultad: "base" },
  { id: "PV1-015", doc: "PV1", tema: "Mapa de valor", tipo: "multiple", pregunta: "Un 'creador de alegría' responde a preguntas del equipo como:", opciones: ["¿Cómo le ahorramos tiempo, esfuerzo o dinero y le cumplimos lo que sueña?", "¿Cómo le quitamos trabas y le abaratamos el esfuerzo?", "¿Cómo le reducimos los miedos antes de comprar?", "¿Cómo le simplificamos los pasos que hoy le cuestan?"], respuesta: 0, explicacion: "Creadores = cómo cumplir sus sueños, ahorrar tiempo/esfuerzo/dinero, mejorar la tecnología y facilitar la adopción.", fuente: "PV1 - creadores", dificultad: "base" },
  { id: "PV1-016", doc: "PV1", tema: "Ejemplo Tutorez", tipo: "multiple", pregunta: "Caso Tutorez: padres sin tiempo para ayudar con tareas, con muchas opciones de tutores y sin saber cuál conviene. Si ofreces reserva en línea, tutores verificados con calificaciones públicas y pago en línea, ¿qué estás construyendo?", opciones: ["El encaje entre frustraciones/alegrías de los padres y tu mapa de valor", "Solo un listado de precios de tutores", "Una campaña para contratar maestros de escuela", "Un catálogo de libros de texto"], respuesta: 0, explicacion: "El caso conecta dolores (sin tiempo, desconfianza, exceso de opciones) con aliviadores (verificación, calificaciones) y creadores (reserva y pago en línea): eso es el encaje.", fuente: "PV1 - ejemplo Tutorez", dificultad: "detalle" },
  { id: "PV1-017", doc: "PV1", tema: "Ejemplo Tutorez", tipo: "multiple", pregunta: "Caso Tutorez: los padres desconfían porque no conocen al tutor. ¿Cuál de estas acciones alivia ESA frustración?", opciones: ["Mostrar estándares de selección, calificaciones y comentarios públicos de otros padres", "Cobrar solo en efectivo y sin factura", "Eliminar la reserva en línea", "Ocultar los comentarios de otros clientes"], respuesta: 0, explicacion: "La desconfianza se alivia con evidencia pública de calidad: selección rigurosa, calificaciones y comentarios.", fuente: "PV1 - ejemplo Tutorez", dificultad: "detalle" },
  { id: "PV1-018", doc: "PV1", tema: "Ad Lib", tipo: "multiple", pregunta: "La técnica Ad Lib ordena la propuesta así: 'Nuestro [producto] ayuda a [segmento] que quiere [trabajo] a [reducir un dolor] y [aumentar un beneficio], a diferencia de [competencia]'. ¿Qué le falta a esta frase: 'Somos la mejor app, descárgala ya'?", opciones: ["Todo: no dice a quién ayuda, qué trabajo resuelve, qué dolor reduce ni en qué se diferencia", "Nada, ya es una propuesta completa", "Solo le falta el precio", "Solo le falta el logo"], respuesta: 0, explicacion: "El Ad Lib exige: producto + segmento + trabajo + verbo contra el dolor + verbo hacia la alegría + diferencia frente a competencia.", fuente: "PV1 - Ad Lib", dificultad: "detalle" },
  { id: "PV1-019", doc: "PV1", tema: "Concepto", tipo: "vf", pregunta: "Un buen lente de propuesta de valor: los clientes no compran productos, compran la mejor versión de sí mismos que logran con tu producto. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: las personas no quieren productos, quieren mejores versiones de sí mismas usándolos.", fuente: "PV1 - cierre", dificultad: "base" },
  { id: "PV1-020", doc: "PV1", tema: "Frustraciones", tipo: "multiple", pregunta: "Un estudiante no se inscribe a un curso online por miedo a reprobar y quedar en ridículo ante sus compañeros. Esa frustración es de tipo:", opciones: ["Riesgo, porque teme lo que pasará si la tarea sale mal, incluido el rechazo", "Beneficio esperado, porque desea el certificado", "Producto físico, porque el curso es digital", "Canal de distribución, porque no sabe dónde pagar"], respuesta: 0, explicacion: "Riesgo = el peligro potencial si la tarea sale mal, incluyendo el miedo al rechazo.", fuente: "PV1 - frustraciones", dificultad: "detalle" },

  // ============ PV2 (35) ============
  { id: "PV2-001", doc: "PV2", tema: "Definición", tipo: "multiple", pregunta: "El concepto de Propuesta de Valor nació en la estrategia competitiva cuando un consultor de McKinsey planteó que el cliente compra mucho más que el producto. ¿Quién y cuándo?", opciones: ["Alexander Osterwalder en 2008", "Michael Lanning en 1983", "Michael Porter en 1990", "Philip Kotler en 1975"], respuesta: 1, explicacion: "Michael Lanning (McKinsey, 1983) introdujo el concepto: el cliente evalúa la suma de experiencias positivas y negativas, no solo el producto.", fuente: "PV2 - explicación", dificultad: "detalle" },
  { id: "PV2-002", doc: "PV2", tema: "Definición", tipo: "multiple", pregunta: "Un equipo cree que su propuesta de valor es su eslogan publicitario y su declaración de misión. ¿Cuál es su error?", opciones: ["Confundirla con eslogan, misión o frase publicitaria: la propuesta describe beneficios diferenciales y creíbles para un segmento", "No haber contratado una agencia de publicidad", "Haber elegido un segmento de clientes", "Haber descrito beneficios del producto"], respuesta: 0, explicacion: "La PV no es eslogan, misión, visión ni frase publicitaria: es el conjunto de beneficios diferenciales y creíbles para un segmento.", fuente: "PV2 - qué es", dificultad: "detalle" },
  { id: "PV2-003", doc: "PV2", tema: "Definición", tipo: "multiple", pregunta: "La empresa diseña y ofrece el producto, pero ¿quién decide en última instancia cuánto vale?", opciones: ["El gerente de marketing con su presupuesto", "El cliente, según el aprecio que le genera", "El proveedor de la materia prima", "La entidad que registra la marca"], respuesta: 1, explicacion: "La empresa selecciona, construye y ofrece; el cliente decide el valor final según el aprecio que le despierta.", fuente: "PV2 - qué es", dificultad: "detalle" },
  { id: "PV2-004", doc: "PV2", tema: "Utilidad", tipo: "multiple", pregunta: "Se dice que la propuesta de valor es el centro del modelo de negocio porque:", opciones: ["Ubica a la empresa en el mercado desde el punto de vista del cliente", "Define el logotipo y los colores de la marca", "Fija los salarios del personal", "Sustituye a la contabilidad del negocio"], respuesta: 0, explicacion: "Es el centro porque permite ubicarse en el mercado desde la perspectiva del cliente y articula el resto del modelo.", fuente: "PV2 - para qué sirve", dificultad: "base" },
  { id: "PV2-005", doc: "PV2", tema: "Utilidad externa", tipo: "multiple", pregunta: "Una empresa comunica: 'Resolvemos tu problema de facturación en 10 minutos'. Esa promesa busca captar atención ofreciendo una:", opciones: ["Solución relevante: el cliente se pregunta qué resultado consigue y por qué conviene resolverlo así", "Lista de empleados de la empresa", "Descripción del software interno que usan", "Invitación a visitar sus oficinas"], respuesta: 0, explicacion: "Solución relevante = promesa de resolver un problema importante; el cliente pregunta qué resultado consigue.", fuente: "PV2 - sirve exterior", dificultad: "detalle" },
  { id: "PV2-006", doc: "PV2", tema: "Utilidad externa", tipo: "multiple", pregunta: "Presentar con claridad los principales beneficios de compra para que el cliente dude menos corresponde a:", opciones: ["La concentración de valor: el cliente se pregunta qué gana y si vale el precio", "La concentración de tiendas en un solo local", "Subir los precios sin explicación", "Eliminar las garantías del producto"], respuesta: 0, explicacion: "Concentración de valor = mostrar los beneficios clave para reducir dudas: ¿qué gano?, ¿vale el precio?", fuente: "PV2 - sirve exterior", dificultad: "detalle" },
  { id: "PV2-007", doc: "PV2", tema: "Riesgo", tipo: "multiple", pregunta: "Una empresa compite solo con frases genéricas ('calidad y buen servicio') iguales a las de todos. ¿Qué le espera?", opciones: ["Riesgo en rentabilidad: terminará en guerras de precios y gastando más en publicidad e incentivos", "Ventas automáticas por usar palabras bonitas", "Desaparición inmediata de la competencia", "Costos de operación iguales a cero"], respuesta: 0, explicacion: "Las PV débiles, genéricas u obsoletas amenazan rentabilidad y supervivencia: guerra de precios y más gasto comercial.", fuente: "PV2 - sirve", dificultad: "detalle" },
  { id: "PV2-008", doc: "PV2", tema: "Antecedente", tipo: "multiple", pregunta: "La propuesta de valor tiene como antecedente una famosa estrategia de Porter. ¿Cuál?", opciones: ["La diferenciación: competir siendo único en algo valioso para el cliente", "El liderazgo en costos a toda costa", "El análisis FODA de la empresa", "La mezcla de las 4P"], respuesta: 0, explicacion: "Antecedente: la estrategia de diferenciación de M. Porter.", fuente: "PV2 - explicación", dificultad: "detalle" },
  { id: "PV2-009", doc: "PV2", tema: "Canvas", tipo: "multiple", pregunta: "El método Canvas de modelos de negocio, con la propuesta de valor en el centro, fue desarrollado por:", opciones: ["Michael Lanning desde una consultora", "Alexander Osterwalder a partir de su tesis doctoral", "Gary Fox desde su blog", "Frederick Taylor desde la administración científica"], respuesta: 1, explicacion: "Osterwalder construyó el Canvas desde su tesis doctoral, con la PV en el centro del análisis.", fuente: "PV2 - explicación", dificultad: "detalle" },
  { id: "PV2-010", doc: "PV2", tema: "Contexto mercado", tipo: "vf", pregunta: "En mercados sobresaturados con muchas ofertas similares, la calidad, el precio e incluso el trato ya no diferencian tanto como antes. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: con ofertas similares por todas partes, esos factores perdieron fuerza diferenciadora y el cliente compara varios proveedores.", fuente: "PV2 - explicación", dificultad: "base" },
  { id: "PV2-011", doc: "PV2", tema: "8 pasos", tipo: "multiple", pregunta: "¿Cuál es la secuencia correcta para construir una propuesta de valor?", opciones: ["Diseñar primero la oferta y después buscar a quién vendérsela", "Estudiar primero la demanda (clientes y problemas), luego la oferta diferencial y al final definir y comunicar", "Comunicar primero y después investigar al cliente", "Fijar el precio y luego inventar el beneficio"], respuesta: 1, explicacion: "Ruta del encaje: demanda (cliente-problemas) → oferta diferencial que encaje → definición y comunicación.", fuente: "PV2 - ocho preguntas", dificultad: "detalle" },
  { id: "PV2-012", doc: "PV2", tema: "Paso 1", tipo: "multiple", pregunta: "Para conocer a fondo a tu segmento puedes crear clientes tipo semi-ficticios. ¿Con qué herramientas?", opciones: ["Mapa de empatía, mapa de cliente o recorrido del cliente (customer journey)", "Listas de precios de la competencia", "Organigramas internos de la empresa", "Improvisación sin ninguna técnica"], respuesta: 0, explicacion: "Herramientas de design thinking para idear el cliente tipo: empatía, mapa de cliente, customer journey.", fuente: "PV2 - paso 1", dificultad: "detalle" },
  { id: "PV2-013", doc: "PV2", tema: "Paso 2", tipo: "multiple", pregunta: "Detectaste que tus clientes abandonan el carrito de compra, pero no sabes la causa de fondo. ¿Qué herramienta aplicas?", opciones: ["Diagrama de causas raíz para llegar al fondo del problema", "Subir la publicidad sin diagnosticar la causa", "Cambiar los precios a ciegas", "Preguntar únicamente al dueño qué supone él"], respuesta: 0, explicacion: "Para llegar al fondo del problema central se aplica el diagrama de causas raíz.", fuente: "PV2 - paso 2", dificultad: "base" },
  { id: "PV2-014", doc: "PV2", tema: "Paso 3", tipo: "multiple", pregunta: "Quieres saber en qué tu solución puede superar a la competencia. ¿Qué conviene elaborar?", opciones: ["Un diagrama de valor de la competencia con sus fortalezas y debilidades", "Un análisis de los salarios de tu propio personal", "Un inventario físico de tu bodega", "Una encuesta de clima laboral interno"], respuesta: 0, explicacion: "Paso 3: analizar fortalezas y debilidades de la competencia con un diagrama de valor.", fuente: "PV2 - paso 3", dificultad: "detalle" },
  { id: "PV2-015", doc: "PV2", tema: "Canvas PV", tipo: "multiple", pregunta: "El Canvas de propuesta de valor se trabaja en tres bloques. ¿Cuáles son?", opciones: ["Perfil del cliente, mapa de valor y encaje entre ambos", "Precio, plaza y promoción", "Misión, visión y valores", "Activo, pasivo y patrimonio"], respuesta: 0, explicacion: "Perfil Hipótesis del Cliente (tareas, frustraciones, alegrías) + Mapa Hipótesis de Valor (productos, aliviadores, creadores) + Encaje.", fuente: "PV2 - paso 5", dificultad: "detalle" },
  { id: "PV2-016", doc: "PV2", tema: "Encaje", tipo: "multiple", pregunta: "Ya cruzaste tu mapa de valor con el perfil del cliente en papel. ¿Qué sigue para lograr un encaje real?", opciones: ["Revisar las relaciones, validarlas con entrevistas a clientes de referencia y ajustar de nuevo", "Ajustar los precios y cerrar ventas de inmediato", "Validar una vez e ignorar lo que digan los clientes", "Copiar la propuesta de otro negocio y lanzarla"], respuesta: 0, explicacion: "Encaje = revisar relaciones, validar con entrevistas directas y ajustar de nuevo.", fuente: "PV2 - paso 5 encaje", dificultad: "detalle" },
  { id: "PV2-017", doc: "PV2", tema: "Redacción", tipo: "multiple", pregunta: "Un borrador completo de propuesta de valor debe responder, en orden:", opciones: ["Qué hacemos + a quién + para qué + cómo + en qué nos diferenciamos", "Quién soy + dónde estoy + cuánto tengo", "Precio + plaza + promoción", "Nombre + logo + color"], respuesta: 0, explicacion: "Fórmula: qué hacemos (verbo) + a quién (segmento) + para qué (beneficio) + cómo (producto) + diferenciación.", fuente: "PV2 - paso 6", dificultad: "detalle" },
  { id: "PV2-018", doc: "PV2", tema: "Redacción", tipo: "multiple", pregunta: "Sobre el título o encabezado de tu propuesta de valor, ¿qué es cierto?", opciones: ["Resume el beneficio final en frase corta, porque la primera frase es la que más influye", "Debe ser lo más largo posible para explicar todo", "Conviene usar jerga que el cliente no entienda", "Es mejor no mencionar al cliente"], respuesta: 0, explicacion: "Encabezado: beneficios finales en frase corta; la primera frase atrae la atención y es la que más influye.", fuente: "PV2 - paso 6", dificultad: "detalle" },
  { id: "PV2-019", doc: "PV2", tema: "Factores", tipo: "multiple", pregunta: "Tus recursos no dan para ser el mejor en todo. Según la lógica de factores, ¿qué estrategia sigues?", opciones: ["Superar a la competencia en lo más significativo para el cliente (impulso), cumplir lo básico (aceptable) y descartar lo que no abarcarás (excluido)", "Ser mediocre en todo por igual", "Prometer todos los factores aunque no puedas cumplirlos", "Regalar obsequios baratos como único diferencial"], respuesta: 0, explicacion: "Impulso = superior en lo significativo por dimensión; aceptables = umbral básico; excluidos = lo que no se abarca.", fuente: "PV2 - factores", dificultad: "detalle" },
  { id: "PV2-020", doc: "PV2", tema: "Curva de valor", tipo: "multiple", pregunta: "Analizando tu curva de valor descubres un beneficio que ningún competidor ofrece y que a los clientes les encantaría. Esa decisión es:", opciones: ["CREAR: explorar fuera de los factores actuales del mercado", "ELIMINAR: quitar ese factor por novedoso", "REDUCIR: ofrecerlo por debajo de la competencia", "IGNORAR: mantener todo exactamente igual"], respuesta: 0, explicacion: "ELIMINAR lo no valorado, REDUCIR sin perjudicar, AUMENTAR donde eres mejor y te valoran, CREAR fuera de los factores actuales.", fuente: "PV2 - curva de valor", dificultad: "detalle" },
  { id: "PV2-021", doc: "PV2", tema: "LOGRO", tipo: "multiple", pregunta: "Una multiherramienta de bolsillo que corta, destapa, lija y mide en una sola pieza entrega sobre todo factor de:", opciones: ["Utilidad: una sola aplicación con mayor alcance para varias tareas", "Velocidad: hace todo con inmediatez total", "Nostalgia: recupera tradiciones perdidas", "Pertenencia: afilia a un club exclusivo"], respuesta: 0, explicacion: "Utilidad (logro funcional): mayor alcance de la aplicación, como la navaja multiusos del material.", fuente: "PV2 - factores LOGRO", dificultad: "detalle" },
  { id: "PV2-022", doc: "PV2", tema: "LOGRO", tipo: "multiple", pregunta: "Un banco permite transferir dinero en segundos desde el móvil, a cualquier hora. Ese valor es de:", opciones: ["Velocidad: rapidez y agilidad en lo que el cliente debe hacer", "Diversión: entretenimiento para el ocio", "Responsabilidad social: aporte medioambiental", "Terciarización: derivar servicios a terceros"], respuesta: 0, explicacion: "Velocidad: mayor rapidez y agilidad, incluso inmediatez (como la banca online).", fuente: "PV2 - factores LOGRO", dificultad: "detalle" },
  { id: "PV2-023", doc: "PV2", tema: "GANANCIA", tipo: "multiple", pregunta: "Una alcaldía crea la 'ventanilla única' donde un trámite que exigía 5 oficinas ahora se hace en una sola. Ese valor es de:", opciones: ["Simplificación: menos tareas, esfuerzo y complejidad", "Marca potente: prestigio difícil de imitar", "Nostalgia: rescate del pasado", "Reconocimiento externo: sellos y premios"], respuesta: 0, explicacion: "Simplificación: reduce tareas, dedicación y complejidad (ventanilla única, software integrado).", fuente: "PV2 - GANANCIA", dificultad: "detalle" },
  { id: "PV2-024", doc: "PV2", tema: "GANANCIA", tipo: "multiple", pregunta: "Pedir el supermercado por app y recibirlo en casa sin filas ni cargar bolsas entrega sobre todo:", opciones: ["Comodidad: le facilitas la vida optimizando su tiempo y esfuerzo", "Metodología única de trabajo interno", "Fórmula secreta imposible de replicar", "Nostalgia por el comercio de antes"], respuesta: 0, explicacion: "Comodidad/conveniencia (ganancia emocional): facilitar la vida al cliente.", fuente: "PV2 - GANANCIA", dificultad: "base" },
  { id: "PV2-025", doc: "PV2", tema: "ESTATUS", tipo: "multiple", pregunta: "Un restaurante con 3 estrellas Michelin cobra precios altos y tiene lista de espera. ¿Qué factor sostiene ese precio?", opciones: ["Calidad superior que los clientes están dispuestos a pagar", "Precio bajo para clientes sensibles al precio", "Reducción de costos operativos", "Accesibilidad para todo público"], respuesta: 0, explicacion: "Calidad (estatus funcional): nivel superior tangible o intangible que el cliente paga con gusto.", fuente: "PV2 - ESTATUS", dificultad: "detalle" },
  { id: "PV2-026", doc: "PV2", tema: "ESTATUS", tipo: "multiple", pregunta: "Comprar un perfume de marca icónica o una moto Harley Davidson compra sobre todo:", opciones: ["Marca y estatus: prestigio y pertenencia a un grupo, difíciles de imitar", "Integración de normativas en la empresa", "Organización de tareas y notas", "Rentabilidad financiera garantizada"], respuesta: 0, explicacion: "Marca/status potente: sensación de prestigio y afiliación apreciada.", fuente: "PV2 - ESTATUS", dificultad: "base" },
  { id: "PV2-027", doc: "PV2", tema: "CONFIANZA", tipo: "multiple", pregunta: "Nadie puede replicar la receta secreta de un pollo famoso ni cierta patente farmacéutica. Ese valor es de:", opciones: ["Fórmulas exclusivas con dificultad de réplica externa", "Precio bajo permanente", "Elección amplísima de productos", "Novedad pasajera de temporada"], respuesta: 0, explicacion: "Fórmulas exclusivas: acceso a experiencias únicas que no se tienen con otra entidad.", fuente: "PV2 - CONFIANZA", dificultad: "detalle" },
  { id: "PV2-028", doc: "PV2", tema: "CONFIANZA", tipo: "multiple", pregunta: "Una marca te deja grabar tu nombre en el empaque del producto que compras. Esa estrategia apela a:", opciones: ["Personalización: oferta a medida para que cada cliente se sienta especial", "Terciarización: derivar ventas a franquicias", "Rentabilidad: retorno garantizado del capital", "Reducción de costos de producción"], respuesta: 0, explicacion: "Personalización: adaptación a gustos de cada cliente (nombres en latas, tarjetas con foto, reportajes).", fuente: "PV2 - CONFIANZA", dificultad: "detalle" },
  { id: "PV2-029", doc: "PV2", tema: "Criterios redacción", tipo: "multiple", pregunta: "Evalúa este borrador: 'Ofrecemos soluciones integrales robustas de excelencia para múltiples segmentos con calidad total'. Según el criterio SIMPLE, ¿qué falla?", opciones: ["Mezcla varios mensajes con tecnicismos en vez de un solo mensaje breve y sencillo", "Debería decir más cosas para aprovechar el espacio", "Está bien porque suena técnico y experto", "Le falta una imagen más grande y colorida"], respuesta: 0, explicacion: "Simple = un solo mensaje por propuesta, breve, sencillo y sin tecnicismos; la complejidad genera rechazo.", fuente: "PV2 - criterios", dificultad: "detalle" },
  { id: "PV2-030", doc: "PV2", tema: "Criterios redacción", tipo: "multiple", pregunta: "El criterio de propuesta 'finalista, detallada y concisa' exige que el beneficio:", opciones: ["Sea concreto e imaginable y se comprenda en unos 5 segundos, pudiendo demostrarse", "Sea inspirador aunque nadie lo entienda del todo", "Sea tan amplio que le sirva a cualquier empresa", "Se guarde en secreto para que no lo copien"], respuesta: 0, explicacion: "Debe leerse y comprenderse en ~5 segundos: concreto, imaginable, relevante y demostrable con mediciones.", fuente: "PV2 - criterios", dificultad: "detalle" },
  { id: "PV2-031", doc: "PV2", tema: "Criterios redacción", tipo: "vf", pregunta: "Una propuesta que dice 'somos diferentes, con mejor servicio, calidad, confianza y excelencia' cumple el criterio de ser significativa, porque usa las palabras favoritas del marketing. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 1, explicacion: "Falso: son palabras manidas y frases vacías; lo significativo es describir el éxito tangible del cliente con algo difícil de imitar.", fuente: "PV2 - criterios", dificultad: "detalle" },
  { id: "PV2-032", doc: "PV2", tema: "Difusión", tipo: "multiple", pregunta: "Ya definiste tu propuesta de valor. ¿Dónde debe vivir hacia afuera?", opciones: ["En la web como mensaje principal y en marketing, redes, blog, newsletter y presentaciones", "Solo en un cuaderno privado del gerente", "Solo en los contratos internos", "En ningún canal para que no la copien"], respuesta: 0, explicacion: "La PV es la base de la comunicación externa: web, marketing, redes, blog, newsletter y presentaciones.", fuente: "PV2 - paso 8", dificultad: "base" },
  { id: "PV2-033", doc: "PV2", tema: "Soportes", tipo: "multiple", pregunta: "Quieres medir si tu propuesta de valor funciona en el mercado. ¿Qué soporte observable usas?", opciones: ["Cuadro de indicadores de valor", "Mapa de empatía del cliente", "Diagrama de causas raíz", "Curva de valor de la competencia"], respuesta: 0, explicacion: "Medir = cuadro de indicadores; conocer clientes = mapa de empatía; problema = causas/matriz; competencia = curva de valor.", fuente: "PV2 - aplicaciones", dificultad: "detalle" },
  { id: "PV2-034", doc: "PV2", tema: "Acuerdo de valor", tipo: "vf", pregunta: "La propuesta puede verse como un 'acuerdo': la empresa promete algo real y el cliente la elige por el aprecio que le despierta. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: desde la empresa es promesa real a cambio de la compra; desde el cliente, el motivo principal de compra.", fuente: "PV2 - qué es", dificultad: "detalle" },
  { id: "PV2-035", doc: "PV2", tema: "Valor percibido", tipo: "multiple", pregunta: "Dos empresas venden café de igual calidad y precio, pero una llena su local y la otra no. ¿Qué explica la diferencia desde la propuesta de valor?", opciones: ["El valor es una cuestión de percepción: el vínculo que cada cliente construye con el problema y su solución", "El tamaño del local, que es lo único que importa", "La cantidad de empleados en planilla", "El software contable que usan"], respuesta: 0, explicacion: "El valor es perceptual: la PV debe construir el vínculo entre cómo el cliente interpreta su problema y tu solución especial.", fuente: "PV2 - sirve exterior", dificultad: "detalle" },

  // ============ MKT8 (20) ============
  { id: "MKT8-001", doc: "MKT8", tema: "Objetivo", tipo: "multiple", pregunta: "El trabajo de mercadotecnia de esta semana busca:", opciones: ["Fortalecer el proyecto articulando el CANVAS con mercadotecnia, marca y propuesta de valor", "Dibujar un logo bonito sin pensar en el cliente", "Subir los precios sin justificación", "Cerrar el emprendimiento"], respuesta: 0, explicacion: "Objetivo: fortalecer el proyecto desde lo comercial, articulando CANVAS, mercadotecnia, marca y PV.", fuente: "MKT8 p.1", dificultad: "base" },
  { id: "MKT8-002", doc: "MKT8", tema: "Mercadotecnia", tipo: "multiple", pregunta: "Un equipo cree que mercadotecnia es solo hacer publicidad. ¿Qué les falta entender?", opciones: ["Que es identificar necesidades y diseñar ofertas de valor: orienta producto, precio, canal y comunicación", "Que la publicidad es lo único que existe", "Que publicar sin estrategia es suficiente", "Que vender barato es lo único que importa"], respuesta: 0, explicacion: "Mercadotecnia = identificar necesidades, comprender al cliente y diseñar ofertas de valor; no es solo publicidad.", fuente: "MKT8 p.5", dificultad: "base" },
  { id: "MKT8-003", doc: "MKT8", tema: "CANVAS débil", tipo: "multiple", pregunta: "Revisas un CANVAS que dice clientes: 'todo público', propuesta: 'buen servicio de calidad' e ingresos sin justificar. ¿Qué diagnosticas?", opciones: ["Un CANVAS débil: clientes amplios, propuesta genérica e ingresos poco realistas", "Un CANVAS excelente listo para invertir", "Un problema solo de logotipo", "Un problema solo de horario de atención"], respuesta: 0, explicacion: "Señales débiles: clientes amplios/confusos, PV genérica, canales incoherentes, ingresos irreales, costos superficiales.", fuente: "MKT8 p.4", dificultad: "base" },
  { id: "MKT8-004", doc: "MKT8", tema: "CANVAS", tipo: "multiple", pregunta: "Para verificar que tu CANVAS tiene lógica interna, la pregunta clave es:", opciones: ["¿Hay coherencia entre cliente, canales, ingresos y costos, y quién pagaría?", "¿Cuántos likes tiene la página?", "¿Cuál color es más bonito?", "¿Qué día de la semana es hoy?"], respuesta: 0, explicacion: "Preguntas orientadoras: cliente real, problema específico, PV diferenciada, cómo llega la solución, quién paga y coherencia entre bloques.", fuente: "MKT8 p.4", dificultad: "detalle" },
  { id: "MKT8-005", doc: "MKT8", tema: "Producto", tipo: "multiple", pregunta: "Antes de vender, ¿sobre qué debes tener claridad total?", opciones: ["Qué entregas, qué beneficios funcionales y emocionales das y qué problema resuelves", "El nombre comercial y los colores del logo", "La lista de socios con sus cargos", "El horario de atención al público"], respuesta: 0, explicacion: "Producto/servicio: qué se entrega (bien, servicio o digital), beneficios y problema concreto que resuelve.", fuente: "MKT8 p.6", dificultad: "base" },
  { id: "MKT8-006", doc: "MKT8", tema: "Propuesta de valor", tipo: "multiple", pregunta: "Tu propuesta de valor debe poder responder con claridad:", opciones: ["Qué me hace diferente, qué necesidad resuelvo y por qué debería importarle al cliente", "Cuánto pesa físicamente el producto", "Dónde estudió cada socio", "Cuántos socios tiene el equipo"], respuesta: 0, explicacion: "No es un discurso bonito: es la promesa clara de utilidad o beneficio diferencial.", fuente: "MKT8 p.6", dificultad: "base" },
  { id: "MKT8-007", doc: "MKT8", tema: "Nombre", tipo: "multiple", pregunta: "Propones llamar a tu app de inventarios 'Xqztr Solutions Enterprise International'. Según los criterios, ¿qué problema tiene?", opciones: ["Es confuso, largo y sin relación clara con la propuesta ni el público", "Es demasiado corto y recordable", "Comunica perfectamente el valor", "Es fácil de pronunciar"], respuesta: 0, explicacion: "Nombre: memorable, fácil de pronunciar, coherente con la propuesta y pertinente al público.", fuente: "MKT8 p.7-8", dificultad: "base" },
  { id: "MKT8-008", doc: "MKT8", tema: "Slogan", tipo: "vf", pregunta: "Un buen slogan reemplaza por completo a la propuesta de valor, así que ya no necesitas definirla. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 1, explicacion: "Falso: el slogan no sustituye la PV; es una frase breve que ayuda a recordarla y refuerza el beneficio.", fuente: "MKT8 p.7", dificultad: "detalle" },
  { id: "MKT8-009", doc: "MKT8", tema: "Logo", tipo: "multiple", pregunta: "En esta etapa del proyecto, ¿qué se espera respecto al logo?", opciones: ["Una idea conceptual (color, forma, estilo que represente la esencia), no la versión final", "La gigantografía final ya impresa", "Copiar el logo de una marca famosa", "No pensar todavía en el logo"], respuesta: 0, explicacion: "Se espera el concepto del logo, no la versión final: debe representar la esencia del proyecto.", fuente: "MKT8 p.7", dificultad: "detalle" },
  { id: "MKT8-010", doc: "MKT8", tema: "4P", tipo: "multiple", pregunta: "Un compañero resume su plan comercial en: qué vendo, a cuánto, por dónde y cómo lo comunico. Está aplicando:", opciones: ["Las 4P: producto, precio, plaza y promoción", "Las 4P: personas, procesos, papeles y paredes", "Las 4P: plan, presupuesto, préstamo y pago", "Las 4P: público, privado, parcial y total"], respuesta: 0, explicacion: "Producto (qué valor), precio (cuánto), plaza (cómo llega) y promoción (cómo se da a conocer).", fuente: "MKT8 p.9", dificultad: "base" },
  { id: "MKT8-011", doc: "MKT8", tema: "Precio", tipo: "multiple", pregunta: "Para fijar tu precio con fundamento debes considerar:", opciones: ["Costos, valor percibido, competencia y capacidad de pago, con políticas como paquetes o membresías", "Solo tu intuición del momento", "Copiar el precio del vecino sin analizar", "Elegir un número al azar"], respuesta: 0, explicacion: "Precio con lógica (no intuición) y políticas: promociones, descuentos, membresías, paquetes o versiones.", fuente: "MKT8 p.10", dificultad: "detalle" },
  { id: "MKT8-012", doc: "MKT8", tema: "Plaza", tipo: "multiple", pregunta: "Vendes manualidades a señoras que compran en el mercado municipal, pero solo vendes por una app complicada. ¿Qué falla?", opciones: ["La plaza: el canal no coincide con dónde y cómo compra tu cliente", "El precio, que siempre es el problema", "El logo, que debería ser más grande", "El slogan, que debería rimar"], respuesta: 0, explicacion: "Plaza = cómo llega la solución (presencial, digital, redes, alianzas); debe ser coherente con cliente y recursos.", fuente: "MKT8 p.10", dificultad: "base" },
  { id: "MKT8-013", doc: "MKT8", tema: "Promoción", tipo: "vf", pregunta: "Publicar todos los días en redes, aunque sea sin estrategia ni mensaje claro, ya cuenta como buena promoción. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 1, explicacion: "Falso: promoción no es publicar sin estrategia; el mensaje debe responder al cliente con valor claro.", fuente: "MKT8 p.11", dificultad: "detalle" },
  { id: "MKT8-014", doc: "MKT8", tema: "Promoción", tipo: "multiple", pregunta: "Tu cliente ideal vive en WhatsApp y asiste a ferias locales. ¿Qué combinación promocional tiene más sentido?", opciones: ["WhatsApp Business más demostraciones en ferias y eventos", "Solo anuncios en un idioma que no habla", "Solo volantes en otra ciudad", "No comunicar nada y esperar"], respuesta: 0, explicacion: "Medios coherentes con el cliente: redes, web, recomendación, WhatsApp Business, volantes, ferias, alianzas.", fuente: "MKT8 p.11", dificultad: "base" },
  { id: "MKT8-015", doc: "MKT8", tema: "Investigación", tipo: "multiple", pregunta: "¿Para qué investigar el mercado antes de lanzar?", opciones: ["Confirmar que el problema existe, conocer disposición de pago e identificar competidores en vez de decidir por intuición", "Confirmar que tu idea es perfecta sin preguntar a nadie", "Evitar a los competidores para no preocuparte", "Adivinar los precios sin ningún dato"], respuesta: 0, explicacion: "Investigar reduce la intuición: confirma problema, comportamiento, pago, sustitutos y tendencias.", fuente: "MKT8 p.12", dificultad: "base" },
  { id: "MKT8-016", doc: "MKT8", tema: "Ejemplo StockFácil", tipo: "multiple", pregunta: "Caso StockFácil: plataforma de inventarios para microempresas con slogan 'Control simple para vender mejor'. ¿Por qué ese slogan funciona?", opciones: ["Es breve, refuerza el beneficio y ayuda a recordar la propuesta", "Es largo y confuso como debe ser", "No dice nada del negocio", "Sustituye por completo a la propuesta de valor"], respuesta: 0, explicacion: "Slogan: breve, claro, expresa beneficio o promesa y aporta recordación (sin sustituir la PV).", fuente: "MKT8 p.13", dificultad: "detalle" },
  { id: "MKT8-017", doc: "MKT8", tema: "Ejemplo StockFácil", tipo: "multiple", pregunta: "Caso StockFácil: vende suscripción mensual por web y WhatsApp a microempresas que llevan inventario a mano. ¿Qué muestra ese diseño?", opciones: ["Coherencia entre cliente, precio accesible, canal digital cercano y promoción con prueba gratuita", "Que el canal no importa para nada", "Que el precio debe fijarse al azar", "Que la promoción no necesita demostración"], respuesta: 0, explicacion: "4P coherentes: plataforma simple, suscripción accesible, web + WhatsApp y contenido con demo gratuita.", fuente: "MKT8 p.13", dificultad: "detalle" },
  { id: "MKT8-018", doc: "MKT8", tema: "Ficha", tipo: "multiple", pregunta: "Tu avance de mercadotecnia debe incluir, como mínimo:", opciones: ["Nombre, slogan, logo, producto, cliente, propuesta de valor, precio, canal, promoción y ajustes al CANVAS", "Nombre, slogan y fotos del equipo fundador", "Solo el nombre del representante", "Solo capturas de redes sociales"], respuesta: 0, explicacion: "Ficha mínima de 10 puntos: identidad, oferta, cliente, PV, precio, plaza, promoción y ajustes CANVAS.", fuente: "MKT8 p.15", dificultad: "detalle" },
  { id: "MKT8-019", doc: "MKT8", tema: "Taller", tipo: "multiple", pregunta: "En el taller, tu equipo descubre que su bloque más débil es 'fuentes de ingreso' porque nadie pagaría lo que piden. ¿Qué debes hacer?", opciones: ["Revisar la coherencia problema-cliente-propuesta y ajustar los supuestos débiles", "Cambiar solo el logo y mantener los supuestos", "Inventar ingresos más altos sin validarlos", "Presentar el CANVAS sin revisarlo"], respuesta: 0, explicacion: "Paso 1 del taller: verificar coherencia, identificar bloque fuerte y débil, ajustar suposiciones.", fuente: "MKT8 p.14", dificultad: "base" },
  { id: "MKT8-020", doc: "MKT8", tema: "Identidad", tipo: "vf", pregunta: "Una identidad comercial sirve si ayuda a entender y recordar el proyecto, no si solo se ve bonita. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: la pregunta orientadora es si la identidad ayuda a entender y recordar, más allá de lo estético.", fuente: "MKT8 p.8", dificultad: "detalle" },

  // ============ COST (20) ============
  { id: "COST-001", doc: "COST", tema: "Estructura", tipo: "multiple", pregunta: "¿Para qué te sirve armar la estructura de costos de tu idea digital?", opciones: ["Para saber en qué se invierte y decidir precios, inversión y viabilidad", "Para fijar el horario de atención al público", "Para elegir el nombre de la marca", "Para contratar personal sin definir perfiles"], respuesta: 0, explicacion: "Organiza fijos y variables: muestra la inversión, distribuye recursos y fundamenta precios y viabilidad.", fuente: "COST - estructura", dificultad: "base" },
  { id: "COST-002", doc: "COST", tema: "Fijos vs variables", tipo: "multiple", pregunta: "Tu app paga hosting, dominio, sueldos y licencias cada mes, vendas mucho o poco. Esos costos son:", opciones: ["Fijos, porque no dependen del volumen de ventas", "Variables, porque cambian con cada venta", "Inexistentes, porque lo digital no cuesta", "Impuestos municipales"], respuesta: 0, explicacion: "Fijos = se pagan siempre (hosting, dominio, salarios, licencias). Variables = dependen del uso (comisiones, soporte por demanda).", fuente: "COST - tipos", dificultad: "base" },
  { id: "COST-003", doc: "COST", tema: "Ejemplos", tipo: "multiple", pregunta: "Un servicio de streaming paga más ancho de banda cuantos más usuarios activos tiene. Ese costo es:", opciones: ["Variable, porque cambia con la demanda de uso", "Fijo, porque nunca cambia", "Un impuesto fijo del gobierno", "Una donación voluntaria"], respuesta: 0, explicacion: "Como en Netflix: producción y plataforma son fijos; el ancho de banda por usuarios activos es variable.", fuente: "COST - ejemplos", dificultad: "detalle" },
  { id: "COST-004", doc: "COST", tema: "Ejemplos", tipo: "multiple", pregunta: "Una app de viajes paga a desarrolladores y servidores todos los meses, más una comisión por cada viaje realizado. Clasifica:", opciones: ["Plataforma y desarrollo son fijos; la comisión por viaje es variable", "Todo es fijo sin excepción", "Todo es variable sin excepción", "Nada de eso son costos del negocio"], respuesta: 0, explicacion: "Como en Uber: plataforma/desarrollo = fijos; comisiones y soporte por viaje = variables.", fuente: "COST - ejemplos", dificultad: "detalle" },
  { id: "COST-005", doc: "COST", tema: "Cálculo", tipo: "multiple", pregunta: "¿Cuál es el primer paso para calcular tu costo por usuario?", opciones: ["Listar todos los costos mensuales, fijos y variables", "Adivinar un precio atractivo", "Copiar el precio de la competencia", "No listar nada y estimar a ojo"], respuesta: 0, explicacion: "Paso 1: lista mensual (hosting, sueldos, licencias, publicidad, mantenimiento); luego sumas y divides entre usuarios.", fuente: "COST - cálculo", dificultad: "base" },
  { id: "COST-006", doc: "COST", tema: "Cálculo", tipo: "multiple", pregunta: "Tu negocio gasta $500 al mes en total y proyecta 100 usuarios activos. ¿Cuál es tu costo por usuario?", opciones: ["$5", "$50", "$500", "$0.50"], respuesta: 0, explicacion: "Costo por usuario = total mensual / usuarios = 500 / 100 = $5.", fuente: "COST - ejemplo", dificultad: "base" },
  { id: "COST-007", doc: "COST", tema: "Precio", tipo: "multiple", pregunta: "Tu costo por usuario es $5 y quieres un margen de contribución del 40%. ¿Qué precio debes cobrar?", opciones: ["$8.33", "$7.00", "$5.40", "$9.00"], respuesta: 0, explicacion: "Precio = costo / (1 - margen) = 5 / 0.60 = $8.33. ($7.00 sería sumar el 40% al costo, error típico).", fuente: "COST - margen", dificultad: "detalle" },
  { id: "COST-008", doc: "COST", tema: "Precio", tipo: "multiple", pregunta: "¿Cuál es la fórmula correcta del precio con margen de contribución?", opciones: ["Precio = costo / (1 - % de contribución)", "Precio = costo + margen en dólares sumado directo", "Precio = costo × (1 + margen)", "Precio = margen dividido entre el costo"], respuesta: 0, explicacion: "Fórmula del material: precio = costo por usuario / (1 - margen deseado).", fuente: "COST - margen", dificultad: "detalle" },
  { id: "COST-009", doc: "COST", tema: "Estimación", tipo: "multiple", pregunta: "Para tu primer mes, ¿qué rango de captación se considera una proyección razonable?", opciones: ["Entre el 1% y el 10% de tu mercado objetivo", "El 100% del mercado de una vez", "El 0%, mejor no proyectar", "Siempre exactamente el 50%"], respuesta: 0, explicacion: "Regla para emprendedores: captar entre 1% y 10% del mercado objetivo el primer mes.", fuente: "COST - estimación", dificultad: "detalle" },
  { id: "COST-010", doc: "COST", tema: "Estimación", tipo: "multiple", pregunta: "Tu mercado objetivo son 30,000 estudiantes y proyectas captar el 2% el primer mes. ¿Cuántos usuarios esperas?", opciones: ["600", "60", "6,000", "300"], respuesta: 0, explicacion: "30,000 × 0.02 = 600 usuarios (escenario de ejemplo del material).", fuente: "COST - ejemplo", dificultad: "detalle" },
  { id: "COST-011", doc: "COST", tema: "Canales", tipo: "multiple", pregunta: "Tienes 2,000 seguidores en Instagram y estimas que el 5% descargará tu app. ¿Cuántos usuarios aporta ese canal?", opciones: ["100", "1,000", "10", "200"], respuesta: 0, explicacion: "2,000 × 0.05 = 100. Cruzar canales con el % de mercado da una estimación media más sólida.", fuente: "COST - canales", dificultad: "detalle" },
  { id: "COST-012", doc: "COST", tema: "Canales", tipo: "multiple", pregunta: "Por tamaño de mercado estimas 600 usuarios y por tus canales estimas 100. ¿Cuál es una estimación media sensata?", opciones: ["350, el promedio de ambas estimaciones", "700, la suma de ambas", "100, siempre la menor", "600, siempre la mayor"], respuesta: 0, explicacion: "(600 + 100) / 2 = 350: escenario realista entre el conservador y el optimista.", fuente: "COST - escenarios", dificultad: "detalle" },
  { id: "COST-013", doc: "COST", tema: "Escenarios", tipo: "multiple", pregunta: "¿Por qué conviene presentar escenarios conservador, realista y optimista en vez de un solo número?", opciones: ["Porque muestra el rango posible y hace la proyección justificable en vez de una adivinanza", "Porque los tres números siempre se cumplen exactos", "Porque así no hay que calcular nada", "Porque solo importa el optimista"], respuesta: 0, explicacion: "Escenarios (p. ej. 100 / 350 / 600) transparentan supuestos: alcance, competencia, valor y lanzamiento.", fuente: "COST - escenarios", dificultad: "detalle" },
  { id: "COST-014", doc: "COST", tema: "Modelos ingreso", tipo: "multiple", pregunta: "Tu app será gratis en lo básico y cobrará por funciones avanzadas. Ese modelo es:", opciones: ["Freemium: base gratis más pago por extras", "Suscripción obligatoria desde el primer día", "Licencia de pago único por descarga", "Solo ingresos por anuncios"], respuesta: 0, explicacion: "Freemium = gratis + extras de pago. Suscripción = cobro periódico; licencia = pago único; publicidad = anuncios; afiliados = comisiones.", fuente: "COST - modelos", dificultad: "base" },
  { id: "COST-015", doc: "COST", tema: "Modelos ingreso", tipo: "multiple", pregunta: "Tu sitio ganará dinero mostrando banners de otras marcas a tus visitantes. Ese modelo es:", opciones: ["Publicidad: ingresos por mostrar anuncios", "Suscripción mensual de usuarios", "Licencia de uso por descarga", "Freemium con funciones extra"], respuesta: 0, explicacion: "Publicidad = mostrar anuncios; afiliados = comisiones por ventas referidas.", fuente: "COST - modelos", dificultad: "base" },
  { id: "COST-016", doc: "COST", tema: "Presupuesto", tipo: "multiple", pregunta: "¿Qué debe incluir tu presupuesto de inversión inicial?", opciones: ["Todo lo previo a operar: desarrollo, marca, registro legal, lanzamiento y herramientas", "Solo el gasto del primer día de ventas", "Solo los sueldos de un mes cualquiera", "Solo la publicidad de un mes"], respuesta: 0, explicacion: "Inversión inicial = dinero para lanzar antes de generar ingresos.", fuente: "COST - presupuesto", dificultad: "base" },
  { id: "COST-017", doc: "COST", tema: "Presupuesto", tipo: "multiple", pregunta: "Sumas tu lanzamiento: desarrollo $1,500 + hosting $120 + marketing $300 + registro $200 + licencias $100. ¿Total y recomendación?", opciones: ["$2,220 y conviene presupuestar al menos 6 meses", "$500 y con un mes basta", "$10,000 y sin registrar nada", "$100 y sin marketing"], respuesta: 0, explicacion: "1,500+120+300+200+100 = $2,220; se recomienda presupuestar al menos 6 meses como mínimo.", fuente: "COST - ejemplo presupuesto", dificultad: "detalle" },
  { id: "COST-018", doc: "COST", tema: "Presupuesto", tipo: "vf", pregunta: "El presupuesto de inversión cubre solo lo que gastas después de generar tus primeros ingresos. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 1, explicacion: "Falso: es el dinero necesario ANTES de generar ingresos, y conviene proyectarlo al menos a 6 meses.", fuente: "COST - presupuesto", dificultad: "detalle" },
  { id: "COST-019", doc: "COST", tema: "Aplicación", tipo: "multiple", pregunta: "¿Cuál es el orden correcto para evaluar la viabilidad económica de tu proyecto?", opciones: ["Identificar recursos, clasificar fijos y variables, calcular costo y precio, estimar inversión inicial", "Cobrar primero y pensar después", "No clasificar nada", "Pedir un préstamo sin calcular"], respuesta: 0, explicacion: "Pasos: recursos → fijo/variable → costo por usuario y precio → presupuesto de inversión.", fuente: "COST - aplicación", dificultad: "base" },
  { id: "COST-020", doc: "COST", tema: "Mercado objetivo", tipo: "multiple", pregunta: "Para estimar usuarios primero debes delimitar bien tu mercado. ¿Cuál está bien delimitado?", opciones: ["App de asesoría nutricional para universitarios de 18 a 28 años en zonas urbanas de un país", "App para todo el mundo sin distinción", "Web para bancos suizos sin definir usuario", "No definir ningún mercado"], respuesta: 0, explicacion: "Delimitar = quién, edad, zona (p. ej. 30,000 estudiantes 18-28 urbanos); luego aplicas el 1%-10%.", fuente: "COST - mercado", dificultad: "detalle" },

  // ============ EJPV (10) ============
  { id: "EJPV-001", doc: "EJPV", tema: "Titular", tipo: "multiple", pregunta: "Un buen titular principal de propuesta de valor debe ser:", opciones: ["El beneficio clave, claro y memorable en una frase corta", "Una lista larga de características técnicas", "El historial completo de la empresa", "Los precios de todos los planes"], respuesta: 0, explicacion: "Titular = beneficio clave claro y memorable (p. ej. crear webs profesionales sin programar).", fuente: "EJPV - estructura", dificultad: "base" },
  { id: "EJPV-002", doc: "EJPV", tema: "Subtítulo", tipo: "multiple", pregunta: "¿Qué debe lograr el subtítulo descriptivo?", opciones: ["Explicar qué ofreces, a quién y qué problema resuelves", "Repetir el titular con otras palabras", "Ocultar a quién va dirigido", "Evitar mencionar el problema"], respuesta: 0, explicacion: "Subtítulo = qué ofreces + a quién + qué problema resuelves (p. ej. lanzar tu web en 24 h sin técnicos).", fuente: "EJPV - estructura", dificultad: "detalle" },
  { id: "EJPV-003", doc: "EJPV", tema: "Público", tipo: "multiple", pregunta: "Lees: '...para emprendedores y pequeñas empresas sin conocimientos técnicos...'. Ese fragmento corresponde al elemento:", opciones: ["Público objetivo: a quién va dirigido", "Diferenciador único", "Prueba de respaldo", "Precio del servicio"], respuesta: 0, explicacion: "Público objetivo = a quién va dirigido el producto o servicio.", fuente: "EJPV - estructura", dificultad: "base" },
  { id: "EJPV-004", doc: "EJPV", tema: "Problema", tipo: "multiple", pregunta: "Lees: '...los procesos de desarrollo costosos y tardados hacen perder tiempo y dinero...'. Ese fragmento corresponde al elemento:", opciones: ["Problema o necesidad: el dolor concreto que resuelves", "Beneficio tangible", "Titular principal", "Prueba de respaldo"], respuesta: 0, explicacion: "Problema/necesidad = el dolor concreto (dependencia de técnicos, procesos costosos).", fuente: "EJPV - estructura", dificultad: "base" },
  { id: "EJPV-005", doc: "EJPV", tema: "Beneficio", tipo: "multiple", pregunta: "Lees: '...lanza tu web en menos de un día con mínima inversión...'. Ese fragmento corresponde al elemento:", opciones: ["Beneficio tangible: el resultado que obtiene el cliente", "Público objetivo", "Diferenciador único", "Nombre de la empresa"], respuesta: 0, explicacion: "Beneficio tangible = resultado (autonomía y agilidad digital).", fuente: "EJPV - estructura", dificultad: "base" },
  { id: "EJPV-006", doc: "EJPV", tema: "Diferenciador", tipo: "multiple", pregunta: "Lees: '...a diferencia de otras plataformas, la nuestra está optimizada para marketing y conversión sin código...'. Ese fragmento corresponde al elemento:", opciones: ["Diferenciador único: lo que te distingue de otras alternativas", "Público objetivo", "Problema o necesidad", "Prueba de respaldo"], respuesta: 0, explicacion: "Diferenciador = lo único frente a alternativas.", fuente: "EJPV - estructura", dificultad: "detalle" },
  { id: "EJPV-007", doc: "EJPV", tema: "Prueba", tipo: "multiple", pregunta: "Lees: '...100 usuarios beta aumentaron su conversión 35% en dos meses...'. Ese fragmento corresponde al elemento:", opciones: ["Prueba o respaldo: evidencia inicial como pilotos o testimonios", "Titular principal", "Problema o necesidad", "Diferenciador único"], respuesta: 0, explicacion: "Prueba = evidencia inicial (piloto, testimonios, betas); es el único elemento opcional.", fuente: "EJPV - estructura", dificultad: "detalle" },
  { id: "EJPV-008", doc: "EJPV", tema: "Estructura", tipo: "multiple", pregunta: "¿Cuántos elementos tiene la estructura y cuál es opcional?", opciones: ["7 elementos y la prueba o credibilidad inicial es opcional", "3 elementos y el titular es opcional", "10 elementos y todos son obligatorios", "1 solo elemento"], respuesta: 0, explicacion: "Titular, subtítulo, público, problema, beneficio, diferenciador y prueba (opcional).", fuente: "EJPV - tabla", dificultad: "detalle" },
  { id: "EJPV-009", doc: "EJPV", tema: "Consolidado", tipo: "vf", pregunta: "Una propuesta consolidada debe conectar problema, beneficio y diferencia en un texto fluido, no ser una lista suelta de frases. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: el ejemplo consolidado integra público, problema, beneficio y diferencia en un párrafo coherente.", fuente: "EJPV - consolidado", dificultad: "base" },
  { id: "EJPV-010", doc: "EJPV", tema: "Subtítulo", tipo: "vf", pregunta: "El subtítulo cumple su función si un desconocido entiende qué ofreces, a quién y por qué es útil. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: esa es exactamente su función dentro de la estructura.", fuente: "EJPV - estructura", dificultad: "base" },

  // ============ SEG1 (12) ============
  { id: "SEG1-001", doc: "SEG1", tema: "Concepto", tipo: "multiple", pregunta: "Un 'cliente potencial' (persona) bien construido es:", opciones: ["La representación de tu segmento ideal: quién es, qué hace, piensa, siente y desea", "El tamaño total del mercado medido en dinero", "El perfil de tu competidor más fuerte", "La lista de proveedores del negocio"], respuesta: 0, explicacion: "Permite diseñar para clientes reales: mientras más precisa la representación, mejor los conoces.", fuente: "SEG1 - fundamentos", dificultad: "base" },
  { id: "SEG1-002", doc: "SEG1", tema: "Cantidad", tipo: "multiple", pregunta: "¿Cuántos perfiles de cliente potencial conviene elaborar?", opciones: ["Entre 3 y 8, para cubrir segmentos sin perder realismo", "Uno solo para todo el mundo", "100 perfiles genéricos", "Ninguno, se improvisa"], respuesta: 0, explicacion: "Sin número mágico, pero se recomiendan mínimo 3 y máximo 8.", fuente: "SEG1 - prepárate", dificultad: "detalle" },
  { id: "SEG1-003", doc: "SEG1", tema: "Método", tipo: "vf", pregunta: "El perfil debe basarse en investigación y entrevistas reales, porque fundar todo en suposiciones sesga el resultado. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: usa investigación real, no conjeturas, y cuídate del sesgo del fundador.", fuente: "SEG1 - checklist", dificultad: "base" },
  { id: "SEG1-004", doc: "SEG1", tema: "Información básica", tipo: "multiple", pregunta: "Armas el perfil de una clienta: 27 años, trabaja en consultoría, viste formal, poco tiempo libre, va al gimnasio y sale con amigos. ¿Qué haces bien?", opciones: ["Das información básica concreta y visualizable en vez de 'mujer joven genérica'", "Inventas datos sin investigar", "Omites su ocupación y hábitos", "Describes solo su salario"], respuesta: 0, explicacion: "Información básica = edad, ocupación, nivel, hábitos: debe visualizarse como persona real.", fuente: "SEG1 - ejemplo", dificultad: "detalle" },
  { id: "SEG1-005", doc: "SEG1", tema: "Relación tecnología", tipo: "multiple", pregunta: "Tu clienta usa smartphone y laptop unas 6 horas al día y adopta apps útiles sin miedo. ¿Qué concluyes para tu servicio digital?", opciones: ["Que el canal digital es viable: está familiarizada y dispuesta si le sirve", "Que odia la tecnología", "Que nunca usa el móvil", "Que solo compra en persona"], respuesta: 0, explicacion: "El bloque tecnológico del perfil indica si el canal digital encaja con el cliente.", fuente: "SEG1 - ejemplo", dificultad: "detalle" },
  { id: "SEG1-006", doc: "SEG1", tema: "Gustos", tipo: "multiple", pregunta: "Tu clienta ama su tiempo libre con seres queridos y odia las tareas domésticas como la colada. Esa información te sirve para:", opciones: ["Conectar tu promesa con lo que la hace feliz e infeliz", "Ignorar sus emociones", "Venderle más tareas domésticas", "Subirle el precio"], respuesta: 0, explicacion: "Qué la hace feliz/infeliz orienta motivaciones, dolores y el mensaje.", fuente: "SEG1 - ejemplo", dificultad: "detalle" },
  { id: "SEG1-007", doc: "SEG1", tema: "Motivaciones", tipo: "multiple", pregunta: "Caso lavandería: una profesional sin tiempo quiere ropa limpia sin llevarla en persona. Sus motivaciones para usar el servicio serían:", opciones: ["Ahorrar tiempo, ropa limpia a precio asequible y horarios flexibles", "Gastar más tiempo lavando", "Pagar lo más caro posible", "Tener horarios rígidos"], respuesta: 0, explicacion: "Motivaciones = problemas que intenta resolver y objetivos (ahorro de tiempo, limpieza, flexibilidad).", fuente: "SEG1 - motivaciones", dificultad: "base" },
  { id: "SEG1-008", doc: "SEG1", tema: "Dolores", tipo: "multiple", pregunta: "Caso lavandería: la clienta duda porque entregaría su ropa a desconocidos, teme retrasos y extravíos. Esos son:", opciones: ["Puntos de dolor: frustraciones y objetivos no alcanzados con lo actual", "Motivaciones de compra", "Canales de redes sociales", "Datos de su salario"], respuesta: 0, explicacion: "Dolores = lo que frustra del servicio actual: desconfianza, traslados, retrasos, pérdidas.", fuente: "SEG1 - dolores", dificultad: "detalle" },
  { id: "SEG1-009", doc: "SEG1", tema: "Historia", tipo: "multiple", pregunta: "¿Para qué se inventa una historia de uso dentro del perfil?", opciones: ["Para visualizar una situación hipotética donde el cliente usa tu servicio y validar si encaja", "Para entretener al equipo sin propósito", "Para reemplazar la investigación", "Para inventar precios"], respuesta: 0, explicacion: "La historia prueba el encaje: ¿esta persona, en su vida real, usaría mi servicio así?", fuente: "SEG1 - historia", dificultad: "base" },
  { id: "SEG1-010", doc: "SEG1", tema: "Familiaridad", tipo: "multiple", pregunta: "El perfil incluye una escala del 1 al 10 de familiaridad con servicios como el tuyo. ¿Para qué sirve ese dato?", opciones: ["Para saber cuánta educación y confianza necesita antes de comprar", "Para decorar la plantilla", "Para fijar el salario del cliente", "Para elegir el logo"], respuesta: 0, explicacion: "Familiaridad baja = necesitas educar y generar confianza; alta = puedes ir directo al diferencial.", fuente: "SEG1 - relación", dificultad: "detalle" },
  { id: "SEG1-011", doc: "SEG1", tema: "Testimonio", tipo: "multiple", pregunta: "Cerrar el perfil con una frase que diría el cliente satisfecho sirve para:", opciones: ["Resumir en sus palabras el valor recibido y verificar que el mensaje es creíble", "Rellenar espacio en la plantilla", "Reemplazar las motivaciones", "Evitar entrevistar clientes"], respuesta: 0, explicacion: "La cita futura condensa el valor ('ahorro tiempo, flexible y fiable') y valida el tono del mensaje.", fuente: "SEG1 - frase", dificultad: "detalle" },
  { id: "SEG1-012", doc: "SEG1", tema: "Segmentación", tipo: "vf", pregunta: "Definir bien a quién NO le vendes es tan importante como definir a quién sí, porque no todo el mundo puede ser tu cliente. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: segmentar implica elegir y renunciar; la plantilla parte de que no todos son clientes potenciales.", fuente: "SEG1 - portada", dificultad: "base" },

  // ============ SEG2 (12) ============
  { id: "SEG2-001", doc: "SEG2", tema: "Concepto", tipo: "multiple", pregunta: "El mapa de empatía sirve principalmente para:", opciones: ["Estandarizar lo que sabes del usuario y proteger la investigación de tus sesgos", "Medir el tamaño del mercado en dinero", "Redactar el contrato de alquiler del local", "Calcular los impuestos del negocio"], respuesta: 0, explicacion: "Ilustra actitudes y comportamientos, ordena hallazgos de encuestas/entrevistas y revela huecos de investigación.", fuente: "SEG2 - fundamentos", dificultad: "base" },
  { id: "SEG2-002", doc: "SEG2", tema: "Cuadrantes", tipo: "multiple", pregunta: "¿Cuáles son los 6 cuadrantes del mapa de empatía?", opciones: ["Piensa y siente, oye, ve, dice y hace, dolores y beneficios", "Precio, plaza, producto, promo, personas y papel", "Activo, pasivo, capital, ingreso, gasto y utilidad", "Oler, probar, tocar, oír, ver y hablar"], respuesta: 0, explicacion: "Estructura: qué piensa/siente, qué oye, qué ve, qué dice/hace, puntos de dolor y beneficios.", fuente: "SEG2 - fundamentos", dificultad: "detalle" },
  { id: "SEG2-003", doc: "SEG2", tema: "Clasificación", tipo: "multiple", pregunta: "'Voy tarde, necesito un café para llevar' dicho por una clienta apurada corresponde al cuadrante:", opciones: ["Qué dice y hace: actitud en público y comportamiento", "Qué piensa y siente en privado", "Qué oye de sus amigos", "Beneficios que desea"], respuesta: 0, explicacion: "Dice/hace = actitud pública, apariencia y comportamiento observable.", fuente: "SEG2 - dice", dificultad: "detalle" },
  { id: "SEG2-004", doc: "SEG2", tema: "Clasificación", tipo: "multiple", pregunta: "'Me preocupa el medioambiente pero ando estresada y sin tiempo' corresponde al cuadrante:", opciones: ["Qué piensa y siente: prioridades, preocupaciones y aspiraciones", "Qué dice y hace en público", "Qué oye de su jefe", "Qué ve en Instagram"], respuesta: 0, explicacion: "Piensa/siente = mundo interior: prioridades, miedos, aspiraciones.", fuente: "SEG2 - piensa", dificultad: "detalle" },
  { id: "SEG2-005", doc: "SEG2", tema: "Clasificación", tipo: "multiple", pregunta: "'Todos mis compañeros van a Starbucks' como dato del entorno corresponde al cuadrante:", opciones: ["Qué ve: medioambiente, amigos y ofertas del mercado", "Qué piensa y siente", "Puntos de dolor", "Beneficios deseados"], respuesta: 0, explicacion: "Ve = entorno observable: amigos, mercado, ofertas, referentes visibles.", fuente: "SEG2 - ve", dificultad: "detalle" },
  { id: "SEG2-006", doc: "SEG2", tema: "Clasificación", tipo: "multiple", pregunta: "'Mis amigos opinan que el café de especialidad vale la pena' corresponde al cuadrante:", opciones: ["Qué oye: lo que dicen familia, amigos, jefe y referentes", "Qué dice y hace", "Puntos de dolor", "Beneficios"], respuesta: 0, explicacion: "Oye = influencias de otros: amigos, familia, jefe, referentes.", fuente: "SEG2 - oye", dificultad: "base" },
  { id: "SEG2-007", doc: "SEG2", tema: "Clasificación", tipo: "multiple", pregunta: "'Me parece caro, hay demasiadas opciones y no sé por qué cambiaría de café' corresponde al cuadrante:", opciones: ["Puntos de dolor: miedos, frustraciones y obstáculos", "Beneficios deseados", "Qué dice y hace", "Qué oye"], respuesta: 0, explicacion: "Dolores = frenos: precio, desconfianza ante lo nuevo, exceso de opciones.", fuente: "SEG2 - dolores", dificultad: "detalle" },
  { id: "SEG2-008", doc: "SEG2", tema: "Clasificación", tipo: "multiple", pregunta: "'Quiero que sepa genial, con varios sabores, orgánico y cerca de mi casa' corresponde al cuadrante:", opciones: ["Beneficios: deseos, necesidades y medidas de éxito", "Puntos de dolor", "Qué oye", "Qué dice y hace"], respuesta: 0, explicacion: "Beneficios = lo que desea y cómo mide el éxito.", fuente: "SEG2 - beneficios", dificultad: "detalle" },
  { id: "SEG2-009", doc: "SEG2", tema: "Método", tipo: "vf", pregunta: "En el mapa, cada idea va en su propia nota adhesiva y puedes agregar todas las que necesites. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 0, explicacion: "Verdadero: un pensamiento = una nota; sin límite de notas.", fuente: "SEG2 - método", dificultad: "base" },
  { id: "SEG2-010", doc: "SEG2", tema: "Requisito", tipo: "vf", pregunta: "Puedes hacer un mapa de empatía útil inventando todo desde cero, sin ninguna investigación ni persona previa. Verdadero o falso?", opciones: ["Verdadero", "Falso"], respuesta: 1, explicacion: "Falso: parte de una persona ya creada y de investigación real (entrevistas, encuestas); si no, solo refleja tus suposiciones.", fuente: "SEG2 - ejemplo", dificultad: "detalle" },
  { id: "SEG2-011", doc: "SEG2", tema: "Propósito", tipo: "multiple", pregunta: "Al terminar el mapa descubres cuadrantes casi vacíos. ¿Qué significa?", opciones: ["Que te falta investigación en esos frentes y debes salir a preguntar", "Que el mapa quedó mal y hay que botarlo", "Que esos cuadrantes no importan", "Que ya puedes lanzar sin más datos"], respuesta: 0, explicacion: "El mapa revela huecos: al juntar todo ves qué investigación falta para priorizar necesidades.", fuente: "SEG2 - por qué", dificultad: "base" },
  { id: "SEG2-012", doc: "SEG2", tema: "Uso", tipo: "multiple", pregunta: "¿Cuál es el producto final esperado del mapa de empatía?", opciones: ["Necesidades priorizadas para diseñar valor que sí le sirva al usuario", "Un informe financiero del negocio", "Una lista de proveedores", "Un organigrama del equipo"], respuesta: 0, explicacion: "Meta: priorizar necesidades y diseñar producto o servicio con valor real.", fuente: "SEG2 - por qué", dificultad: "base" }
];
